version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/jorres/jira-tui"

[[analyzers]]
name = "shell"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true
