version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
    main: ./cmd/jira/main.go
    binary: jira
    ldflags:
      - -s -w -X github.com/jorres/jira-tui/internal/version.GitCommit={{.Commit}}
      - -X github.com/jorres/jira-tui/internal/version.BuildTime={{.Date}}
      - -X github.com/jorres/jira-tui/internal/version.Version={{.Tag}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'